### ISSUE TITLE
Avatar upload fails

### ISSUE THREAD

**Issue by dankibler** [mlabieniec/AngularMaterialPWA#3]
Michael - thanks for this comprehensive sample app. Most things are working, but I'm having a problem with the avatar image upload. I'm getting a 403 error on Storage.put(). The bucket exists and has full permissions for the root account. Is this a Cognito problem? Where should I look to find the problem?

Thanks
Dan

**Comment by dankibler** [comment]
I think I've solved this. I edited file /amplify/backend/storage/s30b834386/parameters.json.
Changed:

- "s3PermissionsAuthenticatedPrivate": "DISALLOWED",

To:
-  "s3PermissionsAuthenticatedPrivate": "s3:GetObject,s3:PutObject",

Shouldn't the "amplify add storage" command taken care of this? Maybe I answered the questions wrong.

**Comment by mlabieniec** [comment]
@dankibler I think what happened here is you may have answered the permissions incorrectly since this is basically giving authenticated users permissions to upload and the cli would do this for you. You could also rerun amplify storage update and reconfigure the options. Let me know if you still run into any issues here
